apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev
spec:
  selector:
    matchLabels:
      run: dev
  replicas: 6
  template:
    metadata:
      labels:
        run: dev
    spec:
      containers:
      - name: dev
        image: redis
        ports:
        - containerPort: 80
      tolerations:
        - key: "platform"
          operator: "Equal"
          value: "sandbox"
          effect: "NoExecute"